### ISSUE TITLE
JSON / Signing problem debugging

### ISSUE THREAD

**Issue by StuartFarmer** [Lamden/lamden-unity-csharp#1]
I'm trying to figure out why some payloads signed with Python give different signatures than with C# / JS.

What is this line doing?
https://github.com/Lamden/lamden-Csharp/blob/67075d7ed70e1180db9c8b893f8835ac7e50585f/Assets/LamdenUnity/Core/Transactions/TxInfo.cs#L38

**Comment by paul-donald** [comment]
This issue has been resolved on the server side code.
